#modified from default_run_pdm_score_gpu.yaml
hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra # Store hydra's config breakdown here for debugging
  searchpath: # Only <exp_dir> in these paths are discoverable
    - pkg://navsim.planning.script.config.common
  job:
    chdir: False
  hydra_logging:
    level: ERROR
  job_logging:
    level: ERROR

defaults:
  - default_common
  - default_evaluation
  - ddp
  - scorer: pdm_scorer
  - agent: gtrs_diffusion_policy
  - _self_
  - override train_test_split: navtest

# Minimal experiment identifiers so Hydra's output_dir can be resolved without extra env vars
experiment_name: diffusion_inference
output_dir: ./outputs/${experiment_name}/${experiment_uid}

simulator:
  _target_: navsim.planning.simulation.planner.pdm_planner.simulation.pdm_simulator.PDMSimulator
  _convert_: "all"
  proposal_sampling: ${proposal_sampling}
